annotations:
  catalog.cattle.io/display-name: Opni Agent
  catalog.cattle.io/os: linux
  catalog.cattle.io/namespace: opni
  catalog.cattle.io/release-name: opni-agent
apiVersion: v2
appVersion: 0.12.1
dependencies:
- condition: kube-prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: file://./charts/kube-prometheus-stack
description: Opni Agent
name: opni-agent
type: application
version: 0.12.1
